title: "JustDeiz Eclipse Repo"
email: justdeiz@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  JustDeiz's Repo for the Eclipse Emulator
baseurl: "" # the subpath of your site, e.g. /blog
url: ""https://justdeiz.github.io/eclipse""
twitter_username: justdeiz
github_username:  justdeiz

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
